"""First migration

Revision ID: 339abd4672b8
Revises: 
Create Date: 2024-10-04 15:31:49.089895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339abd4672b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
